/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import secp256k1 from 'react-native-secp256k1';

export default class App extends Component<{}> {
  state = {
    privKey: '',
    pubKey: '',
  };
  async componentDidMount() {
    const privKey = await secp256k1.ext.generateKey();

    const pubKey = await secp256k1.computePubkey(privKey, true);

    // sign verify
    const data = "1H1SJuGwoSFTqNI8wvVWEdGRpBvTnzLckoZ1QTF7gI0";
    const sigA = await secp256k1.sign(data, privKey);
    console.warn(privKey, '-', pubKey);
    console.warn("verify: ", await secp256k1.verify(data, sigA, pubKey));

    this.setState({privKey, pubKey});
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆RNSecp256k1 example☆</Text>
        <Text style={styles.welcome}>Priv Key: {this.state.privKey}</Text>
        <Text style={styles.welcome}>Pub Key: {this.state.pubKey}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
